feat: Added reusable-android-demo-shop-publish.yaml
rees46/workflow pull request #242
Opened 2024-10-17 14:53 UTC by DanielGreenEngineer

- https://github.com/rees46/planning/issues/1838

2024-10-17 16:48 UTC, Nelfimov requested changes

2024-10-17 16:48 UTC, Nelfimov commented on .github/workflows/reusable-android-demo-shop-publish.yaml
> +          serviceAccountJsonPlainText: ${{ secrets.PLAY_ACCOUNT_AS_BASE64 }}
вот тут не прокатит - у тебя экшен ожидает json текстом, а PLAY_ACCOUTN_AS_BASE64 - это файл который ты мне скидывал в base64. Надо:
- либо перезаписать секрет, положив туда именно JSON, но тогда и изменить нейминг
- либо сделать шаг до этого, который бы преобразовывал секрет из base64 в файл (см. шаг `Create Keystore file`), потом оттуда читал содержимое и передавал сюда

2024-10-17 16:48 UTC, Nelfimov commented on .github/workflows/reusable-android-demo-shop-publish.yaml
> +      - name: Bump version
в твоем демо приложении точно есть этот скрипт? Я помню его делал только для SDK

2024-10-17 16:48 UTC, Nelfimov commented
и нейминг экшена пересмотри - тут правильнее указать, что паблиш в Google Play

2024-10-18 10:03 UTC, DanielGreenEngineer commented on .github/workflows/reusable-android-demo-shop-publish.yaml
> +      - name: Bump version
Да скрипт точно есть, так как я его добавил прежде чем писать конфиг

2024-10-18 10:07 UTC, DanielGreenEngineer commented on .github/workflows/reusable-android-demo-shop-publish.yaml
> +          serviceAccountJsonPlainText: ${{ secrets.PLAY_ACCOUNT_AS_BASE64 }}
Давай перезапишем секреты, сейчас вышлю в личку два файла в форматах base64. 
Раскодирование из файла в джейсон добавил

2024-10-18 10:08 UTC, DanielGreenEngineer commented
> и нейминг экшена пересмотри - тут правильнее указать, что паблиш в Google Play

Переименовал.

2024-10-18 11:32 UTC, Nelfimov requested changes

2024-10-18 11:32 UTC, Nelfimov commented on .github/workflows/reusable-android-google-play-publish.yaml
> +          serviceAccountJsonPlainText: ${{ steps.decode.outputs.playJson }}
у тебя этого степа нет. Когда ты так вызываешь, ожидается что этому шагу предшествует другой с `id: decode`

2024-10-18 11:51 UTC, DanielGreenEngineer commented on .github/workflows/reusable-android-google-play-publish.yaml
> +          serviceAccountJsonPlainText: ${{ steps.decode.outputs.playJson }}
Действительно. Упустил этот шаг. Добавил присвоение значения переменной, верно ли?

2024-10-18 12:02 UTC, DanielGreenEngineer commented on .github/workflows/reusable-android-google-play-publish.yaml
> +          echo "::set-output name=playJson::$(cat google-play-service-account.json)"
Посмотри пожалуйста, таким образом?

2024-10-18 12:05 UTC, Nelfimov commented on .github/workflows/reusable-android-google-play-publish.yaml
> +          echo "::set-output name=playJson::$(cat google-play-service-account.json)"
Да

2024-10-23 06:09 UTC, merged