feat(reusable-docker-publish-infrastructure.yaml): ssh private ansibl…
rees46/workflow pull request #244
Opened 2024-10-25 17:00 UTC by ChernyakIA

…e key

https://github.com/rees46/planning/issues/1888

2024-10-25 17:15 UTC, Nelfimov requested changes

2024-10-25 17:15 UTC, Nelfimov commented on .github/workflows/reusable-docker-publish-infrastructure.yaml
>            PRIVATE_KEY: ${{ secrets.SVC_CICD_PRIVATE_KEY }}
не создавай новую переменную а переделай старую

2024-10-28 09:08 UTC, ChernyakIA commented on .github/workflows/reusable-docker-publish-infrastructure.yaml
>            PRIVATE_KEY: ${{ secrets.SVC_CICD_PRIVATE_KEY }}
Изменил

2024-10-28 09:39 UTC, Nelfimov approved these changes

2024-10-28 10:56 UTC, TorinAsakura approved these changes

2024-10-28 10:56 UTC, merged