feat(deploy-node-trigger): add params to inputs
rees46/workflow pull request #249
Opened 2024-12-24 15:52 UTC by OsirisAnubiz

2024-12-24 16:02 UTC, OsirisAnubiz commented
Пример вызова:
```yml
name: Deploy trigger for Jenkins

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Version, publish and release
    types:
      - completed

jobs:
  build-and-push:
    name: Trigger Jenkins job
    uses: rees46/workflow/.github/workflows/deploy-node-trigger.yaml@master
    with:
      job_name: 'cdn.rees46.com'
      params: |
        [
          { "name": "COMMIT_HASH", "value": ${{ github.sha }}" },
          { "name": "BRANCH_NAME", "value": "master" }
        ]
    secrets:
      URL: ${{ secrets.JENKINS_URL }}
      USER: ${{ secrets.JENKINS_DEPLOY_USER }}
      TOKEN: ${{ secrets.JENKINS_DEPLOY_TOKEN }}
```

2024-12-24 17:45 UTC, Nelfimov requested changes
Страшно, не считаешь? Инпут не типизирован, никак не валидируется. Мне кажется устанешь его настраивать

2024-12-24 17:53 UTC, OsirisAnubiz commented
> Страшно, не считаешь? Инпут не типизирован, никак не валидируется. Мне кажется устанешь его настраивать

Да, есть такая проблема.

Как вариант добавить параметры, которые нужны на данный момент (то что доставалось из спуленого контейнера для воркеров) и оставить так. Потом если понадобяться ещё параметры, которые передаются, то просто добавить их. Всяким опциональным параметрам просто поставить `required: false` и потом не доклеивать в параметры.

Я вижу такое решение. Вроде добавить доп. параметры при необходимости не сильная проблема.

Возможно ты знаешь какой-то способ передать массив?

2024-12-25 06:06 UTC, Nelfimov commented
> Возможно ты знаешь какой-то способ передать массив?

Обычно передается массив из примитивов, разделенных запятой.

Таска уже превращается во что-то огромное. Сделай отдельный экшен который будет заточен чисто на деплой новых образов. Если нужна будет помощь со стороны опсов для доработки джоб jenkins - привлекай

2024-12-25 10:59 UTC, Nelfimov approved these changes

2024-12-25 10:59 UTC, merged